# yazi.toml
[manager]
show_hidden = true

#1/8 width for parent, 3/8 width for current, 4/8 width for preview
ratio = [1, 3, 4] 

#Sort naturally, e.g. 1.md < 2.md < 10.md
sort_by = "natural"
sort_dir_first = true 

[theme]
foreground = "7"   # White
background = "0"   # Black
selection_foreground = "0" # Black for selection text
selection_background = "3" # Yellow for selected text background
directory = "4"    # Blue for directories
file = "7"         # White for files
executable = "2"   # Green for executables
symlink = "9"      # Cyan for symlinks
block_device = "1" # Red for block devices
char_device = "5"  # Magenta for character devices
socket = "6"       # Cyan for sockets
fifo = "3"         


